name: Python Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Make script executable
      run: chmod +x setup_nlp_env.sh

    - name: Install dependencies using script
      run: ./setup_nlp_env.sh

#    - name: Set PYTHONPATH
#      run: echo "PYTHONPATH=$(pwd)/src" >> $GITHUB_ENV  # Set PYTHONPATH to include src


    - name: Run tests
      run: |
        source nlp_env/bin/activate
        mkdir -p tests/reports
        pytest tests --junit-xml=tests/reports/results.xml
#        pytest tests --junit-xml=tests/reports/results.xml --cov=./src --cov-report=xml:tests/reports/coverage.xml


    - name: Upload test reports
      uses: actions/upload-artifact@v4
      with:
        name: test-reports-${{ github.run_id }}-${{ github.event.pull_request.number || github.run_number }}-${{ github.event_name }}
        path: tests/reports
